markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "一盏灯，一部随身听，一本书"

author: "Tsong khapa"
atom-baseurl: "http://blog.tk-zh.com"
disqus: "mba811"

baseurl: /blog

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Music
    class: fa fa-film
    href: http://music.tk-zh.com
  - title: Wiki
    class: fa fa-link
    href: /links.html
    href: http://wiki.tk-zh.com
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml
